const fs = require('fs');
const path = require('path');

const sectionsDir = path.join(__dirname, '..', 'data', 'sections');
const outDir = path.join(__dirname, '..', 'data', 'sections_en');

// Field type translations
const TYPE_MAP = {
  '字符串': 'string',
  '整数': 'int',
  '浮点数': 'float',
  '布尔': 'bool',
  '文件路径': 'file path',
  '整数 / 浮点数': 'int / float',
  '浮点数 / s': 'float / s',
  '枚举': 'enum',
  '字符串列表': 'string(s)',
  '整数列表': 'int(s)',
};

// Description translations for each section
const DESCRIPTIONS = {
  core: {
    name: 'Unique unit identifier (used in code references)',
    displayText: 'Name visible to players',
    displayDescription: 'Unit description (\\n for line break)',
    displayLocaleKey: 'Translation file key (1.15)',
    price: 'Cost (supports multi-resource: credits=500, gold=5)',
    maxHp: 'Maximum health',
    mass: 'Mass/weight (affects collision and transport)',
    radius: 'Collision radius',
    buildSpeed: 'Build time/speed (supports decimal speed or seconds like 3s)',
    techLevel: 'Tech level 1/2/3',
    isBio: 'Is a biological unit',
    isBuilder: 'Is a builder unit',
    nanoFactorySpeed: 'Factory build speed multiplier (1.13)',
    isBuilding: 'Is a building',
    isLocked: 'Disable building',
    isUnselectable: 'Cannot be selected',
    fogOfWarSightRange: 'Sight range (pixels)',
    isAutoSelect: 'Auto-select when built',
    startSlowUpdate: 'Start with slow update cycle',
    isShieldEnabled: 'Shield enabled',
    isSelectableWhileRallying: 'Selectable while rallying',
    isTransport: 'Is a transport unit',
    transportSlots: 'Transport capacity (number of slots)',
    transportWeight: 'Max transport weight',
    transportFlags: 'Transport restriction flags',
    transportFlagsRequired: 'Required transport flags',
    transportFullHp: 'Full HP when transported',
    transportFullAmmo: 'Full ammo when transported',
    transporterResurrection: 'Resurrection on transporter death',
    transportHealAmount: 'Heal rate while in transport',
    isStealth: 'Is a stealth unit',
    stealthRadius: 'Stealth detection radius',
    selfRegenRate: 'Passive health regen rate',
    maxShield: 'Maximum shield HP',
    shieldRegen: 'Shield regen rate',
    energyMax: 'Max energy (used as ammo for weapons)',
    energyRegen: 'Energy regen rate',
    energyStartingPercentage: 'Starting energy percentage',
  },
  graphics: {
    total_frames: 'Total spritesheet frames',
    image: 'Unit sprite path',
    image_wreak: 'Wreck sprite path',
    image_turret: 'Turret sprite path',
    image_shadow: 'Shadow sprite (AUTO for auto)',
    shadowOffsetX: 'Shadow offset X',
    shadowOffsetY: 'Shadow offset Y',
    image_wreak_destroyed: 'Destroyed wreck sprite',
    image_turret_wreak: 'Turret wreck sprite',
    image_turret_wreak_destroyed: 'Destroyed turret wreck sprite',
    image_back: 'Rear sprite (for layered rendering)',
    image_shield: 'Shield sprite',
    image_mask: 'Team color mask sprite',
    image_mask_wreak: 'Team color mask for wreck',
    image_mask_turret: 'Team color mask for turret',
    image_icon: 'Custom icon sprite',
    turretTurnWhenNoTarget: 'Turret turns when no target',
    hideTurretWhileFiring: 'Hide turret while firing',
    mirrorTurret: 'Mirror turret sprite',
    animation_moving_start: 'Moving animation start frame',
    animation_moving_end: 'Moving animation end frame',
    animation_moving_speed: 'Animation speed',
    animation_moving_loop: 'Loop moving animation',
    animation_idle_start: 'Idle animation start frame',
    animation_idle_end: 'Idle animation end frame',
    animation_idle_speed: 'Idle animation speed',
    animation_idle_loop: 'Loop idle animation',
    animation_building_start: 'Building animation start frame',
    animation_building_end: 'Building animation end frame',
    animation_building_speed: 'Building animation speed',
    dustEffect: 'Movement dust effect',
    splastEffect: 'Water splash effect',
    movementEffect: 'Custom movement effect',
    waterMovementEffect: 'Water movement effect',
    waterMovementEffectMinSpeed: 'Min speed for water effect',
    waterMovementEffectMaxSpeed: 'Max speed for water effect',
    trailEffect: 'Trail effect',
    trailEffectMinSpeed: 'Min speed for trail',
    trailEffectMaxSpeed: 'Max speed for trail',
    max_frame_skip: 'Max frame skip for animation',
    hideScorchMark: 'Hide scorch mark on death',
    showHealthBar: 'Show health bar',
    showHealthBarOnlyOnSelection: 'Show health bar only when selected',
    showEnemyHealthBar: 'Show enemy health bar',
    showEnemyHealthBarOnlyOnSelection: 'Show enemy health bar only when selected',
    icon_zoomed_out: 'Zoomed-out minimap icon',
    icon_zoomed_out_scale: 'Zoomed-out icon scale',
    icon_zoom_out_distance: 'Zoom-out icon distance',
    icon_build: 'Build queue icon',
    iconImage: 'GUI icon image',
    iconExtraImage: 'Extra GUI icon image',
    iconScale: 'Icon scale',
    teamColoringMode: 'Team color mode',
    drawLayer: 'Draw layer (z-order)',
    drawType: 'Draw type',
    displayRadius: 'Display radius (can differ from collision radius)',
    uiTargetRadius: 'UI target radius for attacking/reclaiming',
    shieldRenderRadius: 'Shield render radius',
    shieldDisplayOnlyDeflection: 'Show shield only when deflecting',
    shieldDeflectionDisplayRate: 'Shield deflection fade rate',
  },
  attack: {
    canAttack: 'Can attack',
    canAttackFlyingUnits: 'Can attack flying units',
    canAttackLandUnits: 'Can attack land units',
    canAttackUnderwaterUnits: 'Can attack underwater units',
    canAttackBuildings: 'Can attack buildings',
    canAttackTrees: 'Can attack trees',
    canAttackWalls: 'Can attack walls',
    canAttackMines: 'Can attack mines',
    canAttackAuto: 'Auto-attack',
    turretSize: 'Turret size (pixels)',
    turretTurnSpeed: 'Turret turn speed',
    maxAttackRange: 'Max attack range (pixels)',
    minAttackRange: 'Min attack range (pixels)',
    shootDelay: 'Shoot delay (frames or seconds like 5s)',
    shootCone: 'Shoot cone angle',
    targetBlankArea: 'Can target blank area',
    targetInterval: 'Target acquisition interval',
    weaponTargetInterval: 'Weapon target interval',
    weapons: 'Weapon list',
    targetTeammates: 'Can target teammates',
    targetNeutral: 'Can target neutral units',
  },
  movement: {
    movementType: 'Movement type (LAND/HOVER/AIR/NAVAL/SUB/AMPHIBIOUS)',
    moveSpeed: 'Movement speed',
    moveAccelerationSpeed: 'Acceleration speed',
    moveDecelerationSpeed: 'Deceleration speed',
    maxTurnSpeed: 'Max turn speed',
    turnAcceleration: 'Turn acceleration',
    reverseSpeedPercentage: 'Reverse speed percentage',
    moveSlidingMode: 'Sliding mode',
    moveIgnoringBody: 'Ignore body orientation',
    moveSlidingDir: 'Sliding direction angle',
    moveAnimationInReverse: 'Reverse animation when moving backward',
    pathfindingRadius: 'Pathfinding radius override',
    canBePushed: 'Can be pushed by other units',
    canPush: 'Can push other units',
    turnInPlace: 'Turn in place',
    turnInPlaceTurnSpeed: 'Turn in place speed',
    moveWhileTurning: 'Move while turning',
    canMoveWhileCharging: 'Can move while charging',
    canMoveWhileAttacking: 'Can move while attacking',
    canFlee: 'Can flee when damaged',
  },
  projectile: {
    directDamage: 'Direct damage',
    areaDamage: 'Area damage (AoE)',
    areaDamageRadius: 'AoE radius',
    areaDamageDropStart: 'AoE damage drop-off start',
    areaDamageDropRate: 'AoE damage drop-off rate',
    damageOverTime: 'Damage over time',
    damageOverTimeFrames: 'DoT duration (frames)',
    damageOverTimeDelay: 'DoT delay',
    damageOverTimeEffectId: 'DoT effect ID',
    damageFriendly: 'Can damage friendly units',
    damageCaster: 'Can damage the caster',
    damageBuilding: 'Damage multiplier vs buildings',
    damageAir: 'Damage multiplier vs air',
    damageLand: 'Damage multiplier vs land',
    damageWater: 'Damage multiplier vs water',
    damageSub: 'Damage multiplier vs submarines',
    life: 'Projectile lifetime (frames)',
    speed: 'Projectile speed',
    instant: 'Instant hit (laser type)',
    laserEffect: 'Laser visual effect',
    laserEffectRadius: 'Laser effect radius',
    lineOfSight: 'Requires line of sight',
    homing: 'Homing projectile',
    turnRate: 'Homing turn rate',
    turnRateClose: 'Homing turn rate close to target',
    targetStickiness: 'Target stickiness',
    targetStickinessClose: 'Target stickiness close range',
    keepTargetIfNoLoS: 'Keep target if no line of sight',
    areaDamageTeam: 'AoE damage team filter',
    hitEffect: 'Impact effect',
    hitEffectChance: 'Impact effect chance',
    hitEffectOnCaster: 'Apply hit effect on caster',
    hitEffectOnDeath: 'Apply hit effect on death',
    hitEffectDelay: 'Hit effect delay',
    trailEffect: 'Projectile trail effect',
    trailEffectInterval: 'Trail effect interval',
    trailEffectChance: 'Trail effect chance',
    trailEffectOffset: 'Trail effect offset',
    spawnProjectileOnDeath: 'Projectile spawned on death',
    spawnProjectileOnDeathCount: 'Number of projectiles on death',
    spawnProjectileOnDeathSpread: 'Spread angle on death',
    ignoreShield: 'Ignores shields',
    shieldDamageMultiplier: 'Shield damage multiplier',
    shieldPenetration: 'Shield penetration',
    canAttackGround: 'Can attack ground position',
    canAttackUnderwater: 'Can attack underwater units',
  },
  turret: {
    x: 'Turret mount X offset',
    y: 'Turret mount Y offset',
    projectile: 'Associated projectile ID (e.g., 1, laser)',
    turnSpeed: 'Turret turn speed',
    shoot_sound: 'Shoot sound effect',
    shoot_flame: 'Muzzle flash size',
    recoilOffset: 'Recoil offset',
    recoilOutTime: 'Recoil out time (frames or seconds)',
    recoilReturnTime: 'Recoil return time (frames or seconds)',
    warmup: 'Warmup time (frames)',
    cooldown: 'Cooldown time after firing',
    chargeTime: 'Charge time before firing',
    chargeEffect: 'Charge visual effect',
    minRange: 'Minimum range',
    maxRange: 'Maximum range',
    maxShots: 'Max shots before cooldown',
    reloadTime: 'Reload time',
    shootCone: 'Shoot cone angle',
    multiShot: 'Multi-shot count',
    multiShotSpread: 'Multi-shot spread angle',
    targetType: 'Target type filter',
    targetTeam: 'Target team filter',
    onlyFireOnRoE: 'Only fire when ROE set',
  },
  action: {
    text: 'Button text (supports dynamic text)',
    textPostFix: 'Text postfix (1.15)',
    icon: 'Action icon',
    iconScale: 'Icon scale',
    autoTrigger: 'Auto-trigger condition (LogicBoolean)',
    autoTriggerCheckRate: 'Auto-trigger check rate',
    onAction: 'Action to execute on trigger',
    onAction2: 'Secondary action on trigger',
    onAction3: 'Tertiary action on trigger',
    onAction4: 'Quaternary action on trigger',
    cooldownTime: 'Cooldown time',
    actionDelay: 'Action delay',
    actionDelay2: 'Secondary action delay',
    showInGui: 'Show in GUI',
    showInGuiTeam: 'Show in GUI for team',
    showInGuiIf: 'Show condition (LogicBoolean)',
    hidden: 'Hidden action (not shown in UI)',
    guiOrder: 'GUI sort order',
    onlyShowGuiIf: 'Only show if condition (LogicBoolean)',
  },
  ai: {
    useAsBuilder: 'AI uses as builder',
    useAsAI: 'AI uses this unit',
    aiPriority: 'AI build priority',
    aiMax: 'AI max count',
    aiGroup: 'AI group',
    aiGroupPriority: 'AI group priority',
    aiGroupSize: 'AI group size',
    aiGroupRadius: 'AI group radius',
    aiBuildLocation: 'AI preferred build location',
    aiTargetType: 'AI target type preference',
    aiTargetTeam: 'AI target team preference',
  },
  animation: {
    name: 'Animation name',
    sprite: 'Animation sprite path',
    frames: 'Number of frames',
    speed: 'Animation speed',
    loop: 'Loop animation',
    playOnStart: 'Play on unit start',
    playOnEvent: 'Trigger event',
    playOnce: 'Play once',
    startFrame: 'Start frame',
    endFrame: 'End frame',
  },
  effect: {
    image: 'Effect sprite path',
    lifetime: 'Effect lifetime (frames)',
    x: 'X offset',
    y: 'Y offset',
    rotation: 'Rotation',
    scaleX: 'Scale X',
    scaleY: 'Scale Y',
    alpha: 'Alpha/opacity',
    color: 'Effect tint color (#RRGGBB)',
    fadeIn: 'Fade in time',
    fadeOut: 'Fade out time',
    followUnit: 'Follow the unit',
    teamColored: 'Apply team color',
    randomRotation: 'Random rotation on spawn',
    randomScale: 'Random scale on spawn',
    velocityX: 'Velocity X',
    velocityY: 'Velocity Y',
    gravity: 'Gravity effect',
    attachToBone: 'Attach to bone/turret',
    animation: 'Effect animation',
    animationSpeed: 'Effect animation speed',
    frameSizeX: 'Frame size X',
    frameSizeY: 'Frame size Y',
    spawnEffectOnDeath: 'Spawn this effect on unit death',
    sound: 'Sound effect',
    soundDelay: 'Sound delay',
    soundPitch: 'Sound pitch',
    soundVolume: 'Sound volume',
  },
  canBuild: {
    unit: 'Unit to build',
    buildX: 'Build position X',
    buildY: 'Build position Y',
    buildDelay: 'Build delay',
    buildSpeedMultiplier: 'Build speed multiplier',
    buildAngle: 'Build facing angle',
    produceUnits: 'Produce units list',
    produceUnitsInterval: 'Production interval',
    produceUnitsMax: 'Max produced units',
  },
  decal: {
    image: 'Decal sprite path',
    x: 'X offset',
    y: 'Y offset',
    scaleX: 'Scale X',
    scaleY: 'Scale Y',
    rotation: 'Rotation',
    alpha: 'Alpha/opacity',
    color: 'Tint color (#RRGGBB)',
    teamColored: 'Apply team color',
    drawLayer: 'Draw layer (z-order)',
    frame: 'Animation frame',
  },
  leg: {
    x: 'Leg X offset',
    y: 'Leg Y offset',
    image: 'Leg sprite',
    image_wreak: 'Leg wreck sprite',
    total_frames: 'Total spritesheet frames',
    animation_walking_start: 'Walking animation start frame',
    animation_walking_end: 'Walking animation end frame',
    animation_walking_speed: 'Walking animation speed',
    animation_idle_start: 'Idle animation start frame',
    animation_idle_end: 'Idle animation end frame',
    animation_idle_speed: 'Idle animation speed',
  },
  attachment: {
    x: 'Attachment X offset',
    y: 'Attachment Y offset',
    inheritUnit: 'Inherit from another unit',
    inheritAction: 'Inherit from action',
    inheritAction2: 'Inherit from secondary action',
  },
  placementRule: {
    requireUnit: 'Required unit for placement',
    requireUnitRange: 'Required unit range',
    requireUnitCount: 'Required unit count',
    forbidUnit: 'Forbidden unit nearby',
    forbidUnitRange: 'Forbid unit range',
    requireTerrain: 'Required terrain type',
    forbidTerrain: 'Forbidden terrain type',
    requireHeight: 'Required ground height',
    maxHeight: 'Maximum ground height',
  },
  resource: {
    name: 'Resource name',
    max: 'Maximum resource amount',
    start: 'Starting resource amount',
    regen: 'Regen rate',
    icon: 'Resource icon',
  },
  template: {
    name: 'Template name',
    copyFrom: 'Copy from another file',
  },
  global_resource: {
    name: 'Global resource name',
    icon: 'Global resource icon',
    start: 'Starting global resource',
    max: 'Maximum global resource',
    regen: 'Regen rate',
    shared: 'Shared with team',
  },
};

// Process all section files
for (const file of fs.readdirSync(sectionsDir).sort()) {
  if (!file.endsWith('.json')) continue;
  const filePath = path.join(sectionsDir, file);
  const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));

  const sectionName = data.name;
  const fieldTranslations = DESCRIPTIONS[sectionName] || {};

  for (const field of data.data || []) {
    if (fieldTranslations[field.name]) {
      field.description = fieldTranslations[field.name];
    } else {
      // Fallback: auto-generate English description from field name
      field.description = autoDescribe(field.name, field.type);
    }
  }

  fs.writeFileSync(path.join(outDir, file), JSON.stringify(data, null, 2) + '\n', 'utf8');
  console.log(`✓ ${file} (${data.data.length} fields)`);
}

/**
 * Auto-generate English description from field name
 */
function autoDescribe(name, type) {
  // Split camelCase/PascalCase into words
  const words = name
    .replace(/([A-Z])/g, ' $1')
    .replace(/[_\s]+/g, ' ')
    .trim()
    .toLowerCase()
    .split(' ');

  // Common shorthand expansions
  const expand = {
    max: 'maximum', min: 'minimum', hp: 'hitpoints', ai: 'AI',
    rof: 'rate of fire', los: 'line of sight', hpRegen: 'HP regeneration',
    enable: 'enabled', disable: 'disabled', init: 'initial',
    dir: 'direction', pos: 'position', num: 'number',
    ammo: 'ammunition', dmg: 'damage', dmgT: 'damage vs',
  };

  const expanded = words.map(w => expand[w] || w);

  // First word capitalized
  if (expanded.length > 0) {
    expanded[0] = expanded[0].charAt(0).toUpperCase() + expanded[0].slice(1);
  }

  let description = expanded.join(' ');

  // Add type hint for numbers/bools
  if (type) {
    const t = type.toLowerCase();
    if (t.includes('bool')) description += ' (true/false)';
  }

  return description;
}

console.log(`\nDone! Created ${fs.readdirSync(outDir).length} English section files.`);
